require:
  - rubocop-rails
  - rubocop-rspec

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: compact

AllCops:
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "bin/*" 
    - "config/**/*"
    - "Guardfile"
    - "Rakefile"
    - "node_modules/**/*"

  DisplayCopNames: true