version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome-server # <-- Link to the chrome container
    environment:
      HUB_URL: http://chrome-server:4444
      DOCKER_ACTIVE: true
  chrome-server:
    image: selenium/standalone-chrome:96.0
    volumes:
      - /dev/shm:/dev/shm
